return {
  EPSILON = 0.001,
  DEFAULT_GRAVITY = 0.125,
  GRID_SIZE = 16,
  HUD_HEIGHT = 16,

  -- player
  PLAYER_JUMP_Z_VELOCITY = 2,
  PLAYER_JUMP_GRAVITY = 8,
  PLAYER_HOLE_DOOM_TIMER = 10,
  PLAYER_HOLE_PULL_MAGNITUDE = 15,
  PLAYER_DISTANCE_TRIGGER_HOLE_FALL = 1
}